// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type helloUserMsgT struct {
	_       structs.HostLayout
	Message [12]int8
}

// loadHello returns the embedded CollectionSpec for hello.
func loadHello() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HelloBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hello: %w", err)
	}

	return spec, err
}

// loadHelloObjects loads hello and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*helloObjects
//	*helloPrograms
//	*helloMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHelloObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHello()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// helloSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type helloSpecs struct {
	helloProgramSpecs
	helloMapSpecs
	helloVariableSpecs
}

// helloProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type helloProgramSpecs struct {
	Hello *ebpf.ProgramSpec `ebpf:"hello"`
}

// helloMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type helloMapSpecs struct {
	Output     *ebpf.MapSpec `ebpf:"output"`
	UserConfig *ebpf.MapSpec `ebpf:"user_config"`
}

// helloVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type helloVariableSpecs struct {
}

// helloObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHelloObjects or ebpf.CollectionSpec.LoadAndAssign.
type helloObjects struct {
	helloPrograms
	helloMaps
	helloVariables
}

func (o *helloObjects) Close() error {
	return _HelloClose(
		&o.helloPrograms,
		&o.helloMaps,
	)
}

// helloMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHelloObjects or ebpf.CollectionSpec.LoadAndAssign.
type helloMaps struct {
	Output     *ebpf.Map `ebpf:"output"`
	UserConfig *ebpf.Map `ebpf:"user_config"`
}

func (m *helloMaps) Close() error {
	return _HelloClose(
		m.Output,
		m.UserConfig,
	)
}

// helloVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHelloObjects or ebpf.CollectionSpec.LoadAndAssign.
type helloVariables struct {
}

// helloPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHelloObjects or ebpf.CollectionSpec.LoadAndAssign.
type helloPrograms struct {
	Hello *ebpf.Program `ebpf:"hello"`
}

func (p *helloPrograms) Close() error {
	return _HelloClose(
		p.Hello,
	)
}

func _HelloClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hello_bpfeb.o
var _HelloBytes []byte
